# Generated by Django 5.2.17 on 2026-10-02 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('vacancy_url', models.URLField()),
                ('status', models.CharField(choices=[('sent', 'Отклик отправлен'), ('viewed', 'Отклик просмотрен'), ('declined', 'Отказ'), ('contacted', 'Работодатель связался'), ('interview', 'Собеседование назначено'), ('offer', 'Оффер получен')], default='sent', max_length=200)),
                ('applied_on', models.DateField(default=django.utils.timezone.localdate)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
